title: Prem Kumar G
logo: /assets/img/logo.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin: premgowda98
github_url: premgowda98
mail_address: premkumarmvks@gmail.com
phone_number: +919538507538
location: Bengaluru
